first=int(input("enter a first number:"))
second=int(input("enter a second number:"))
add=(first+second)
sub=(first-second)
div=(first/second)
mul=(first*second)
print("The addition is",add)
print("The Subtraction is",sub)
print("The multiplication is",mul)
print("The division",div)